version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ramkumar
      - POSTGRES_PASSWORD=HacksRK
      - POSTGRES_DB=smart-tnp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
