version: "3"

services:
  # postgres:
  #   image: postgres:15
  #   restart: always
  #   # env_file: .env
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   expose:
  #     - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  smart-tnp-server:
    build: .
    # env_file: .env
    volumes:
      - .:/smart-tnp-server
    ports:
      - 8080:8080
    depends_on:
      # - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    # restart: always

volumes:
  # postgres:
  redis-data:
