services:
  mysqldb:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .:/mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}

  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redis

  smart-tnp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - .:/smart-tnp-server
    depends_on:
      - mysqldb
      - redis-stack-server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

volumes:
  mysql:
  redis-data:
